### ISSUE TITLE
Improve on the GC workflow invocation report

### ISSUE THREAD

**Issue by martenson** [RECETOX/workflow-reports#2]
We now have a skeleton, we need to polish and tune it.

**Comment by hechth** [comment]
Sections
- [ ] Workflow Inputs (Step 1 - 3)
- [ ] Peak Detection (Step 4 - 5) with intermediate apLCMS outputs + conversion, with short desciption of peak detection steps
- [ ] Deconvolution (Step 6 - 7) - inputs, outputs
- [ ] RI Assignment (Step 8)
- [ ] Annotation / Spectral Matching (Step 9)

**Comment by hechth** [comment]
@martenson You think it would also be good to add some background to the actual data which is being used for this specific prototype?

**Comment by martenson** [comment]
@hechth Can't hurt but I wouldn't spend much time on it. The data is arbitrary and the process is more important I believe.

**Comment by martenson** [comment]
I think some of the points were covered when we switched to the new workflow from @hechth here: https://github.com/RECETOX/workflow-reports/pull/6

It could surely use more description of the process though.
